### ISSUE TITLE
Call multiples partials and place in different positions

### ISSUE THREAD

**Issue by williankeller** [chrisjhill/MVC#3]
Hi dear,
How to call multiples partials and how can I do to put in different places, example:
on my index.phtml call a sidebar or a extra footer

**Comment by chrisjhill** [comment]
It depends if you wanted them across all your pages (if so, put it in your layout (`Library/MyProject/Layout/default.phtml`)), or if you wanted them on just a single page (if so, put it in one of your view scripts (`Library/MyProject/View/Script/Index/index.phtml`)).

You can call View Helpers, which take the logic away from the View Scripts, which in turn will return HTML as defined by a view partial. There is a test View Helper already in the code base, so you can try outputting that in the Layout and View Scripts: 

`<?=$this->test(array('string' => 'Hello World'))?>`

**Comment by williankeller** [comment]
Got it, I created helper that puts the parts into variables. I believe that in my case, it is useful
```php
/**
 * Partial View Helper.
 * Render a default partial of site
 */
class Partial extends Core\ViewHelper {

  /**
   * Render a View Helper.
   *
   * @access public
   * @param  array  $params A collection of variables that has been passed to us.
   * @return string         A rendered View Helper Partial template file.
   */
  public function render($params = NULL) {
    //Set default partials
    $default = array('header', 'footer');
    // Check if is an array
    if (!is_array($params)) {
      $params = array($params);
    }
    // Merge partials
    $partials = array_merge($default, $params);
    // Each parts
    foreach ($partials as $partial) {
      // Render and instance parts
      $render = $this->renderPartial($partial, $this->view->_variables);
      $variable["_view" . ucfirst($partial)] = $render;
    }
    // Create variable
    $this->view->addVariable($variable);
  }

}
```
And, if necessary includes one more partial, just pass to `$params`

**Comment by chrisjhill** [comment]
Umm. That's not really how you are supposed to do it. View Helpers should be called dynamically from your View Scripts or Template (e.g., https://github.com/chrisjhill/MVC/blob/master/Library/MyProject/View/Script/Index/index.phtml or https://github.com/chrisjhill/MVC/blob/master/Library/MyProject/Layout/default.phtml).

E.g., your default layout could look something like:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<meta http-equiv="Content-Language" content="en-gb" />
	<title>PHP MVC Framework</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link type="text/css" href="<?=$urlRoot?>assets/css/styles.css" rel="stylesheet" media="screen" />
</head>
<body>
	<div id="header">
		<?=$this->header(['foo' => 'bar'])?>
	</div>

	<div id="sidebar">
		<?=$this->sidebar()?>
	</div>

	<div id="page-content">
		<?=$viewContent?>
	</div>
</body>
</html>
```
