### ISSUE TITLE
Still on the router

### ISSUE THREAD

**Issue by ghost** [chrisjhill/MVC#6]
Firtst Merry Christmas,

Maybe I read the readme badly or maybe I'm not able to read code anymore, but it does not seem like an application designed to be fast and easy to use.

In particular, the ruoter does not seem to have an easy way to create paths or decide which types of data to pass. You do not even understand how to pass something to the view that is not a simple text string.

For example, creating a router like this
```php
$router->addRoute('User')
        ->setRoute('user/welcome/:userId')
        ->setFormat(array(
            'userId'    => '[a-z0-9]+')
        )
        ->setEndpoint(array(
            'controller' => 'User',
            'action' => 'welcome'
            )
        );
```
or like this
```php
$router->addRoute('User')
        ->setRoute('user/welcome')
        ->setFormat(array(
            'userId'    => '[a-z0-9]+')
        )
        ->setEndpoint(array(
            'controller' => 'User',
            'action' => 'welcome'
            )
        );
```
By changing the controller this way
```php
   public function welcomeAction()
    {
        $userId = 10;
        return $userId;
    }
```
and the view in
```php
<?=userId?>
```
it has no effect whatsoever with url `http://mysite/user/welcome` or `http://mysite/user/welcome/userId`

Boh I do not know what to think. Perhaps, if you had time and desire, you could try to write a couple of sample methods.

Among other things, the documentation shows this example
```php
echo $this->url(
	array(
		'controller'      => 'index',
		'action'          => 'hello',
		'variables'       => array('foo' => 'bar'),
		'variable_retain' => true
	)
);
```
but at least not to make a mistake, the `url` method does not even exist anywhere. 

I repeat: I do not know what to think.

For sure it is a good starting point but maybe it would take a hair more documentation.

**Comment by chrisjhill** [comment]
Sorry, you are absolutely right, there is no mention of how to pass variable from Controllers to the View. I'll look into writing documentation and some examples soon, after Christmas.

For the time being, this is an example of how to do that:

```
public function welcomeAction()
    {
        $this->view->addVariable('foo', 'bar');
    }
```

And you can then use that variable, `$foo`, in Layout and View Scripts.

**Comment by chrisjhill** [comment]
Also, for the `Url` function, it's not a function but is instead a View Helper class called `Url`. So, you can find that in `/MyProject/View/Helper/URL.php`.

**Comment by ghost** [comment]
You are great. The example works and looks forward to more information.

**Comment by ghost** [comment]
I do not understand. The `Url` class is one thing but in the example you are simply referring to a method (`$ this->url()`) which is very different from the `Url` class located in `View\Helper`.

Furthermore, the only reference found for a `url` is in the `Request class` but you have declared it `static, private and as a string`, while the example refers to an array similar to that of the `render()` method of the `Url` class but it is not there is no method to refer to with (`$this->url()`).

In the `Url` class, there are also no properties but only the `render()` method.

Can you explain what escapes me since I do not see how you could refer a class with $this, context inside the class, with a class with a different name?

**Comment by chrisjhill** [comment]
`$this->url()` is essentially called in the context of `Core/View`. In that class there is the `__call` magic method which receives the function call `url` and any parameters you passed in. From here we can create the view helper and then call the `render` method on it which will return a string.

The `__call` magic method is only a few lines long - should be an easy read (hopefully!).

**Comment by ghost** [comment]
Ok i understand.
