### ISSUE TITLE
Can't seem to display the profiler stack

### ISSUE THREAD

**Issue by AnnoyingTechnology** [chrisjhill/MVC#8]
Hi (again, a few years later),

I installed MVC, looking to "borrow" your `Profiler` class, as the waterfall from the readme is pretty much what I'm after to implement in [another framework](https://github.com/polyfony-inc/polyfony) but 
* All I find in the [source code](https://github.com/chrisjhill/MVC/blob/master/Library/Core/Profiler.php#L147), is how the raw data is provided by the `Profiler` class,
* The `Profiler` doesn't appear anywhere in the webpage, even though I set it to `true` in `config.ini`

A tiny bit of help ? Thanks

Also, after a clean co 
```
2018-02-19 19:15:35: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Notice:  Undefined index: APP_ENVIRONMENT in /home/julien/Web/domains/mvc/Library/global.php on line 3
```

**Comment by chrisjhill** [comment]
The `APP_ENVIRONMENT` variable is defined in the `.htaccess` file: https://github.com/chrisjhill/MVC/blob/master/Web/.htaccess

The `Profiler` is just concerned with the actual storage of data - the actual output is performed in the ViewHelper (https://github.com/chrisjhill/MVC/blob/master/Library/MyProject/View/Helper/Profiler.php) which is called here in the Core View, at the bottom of the `render` function: https://github.com/chrisjhill/MVC/blob/master/Library/Core/View.php

**Comment by AnnoyingTechnology** [comment]
>The APP_ENVIRONMENT variable is defined in the .htaccess file: https://github.com/chrisjhill/MVC/blob/master/Web/.htaccess

Ok (didn't see that Apache was a requirement)

>The Profiler is just concerned with the actual storage of data - the actual output is performed in the ViewHelper

Great, thanks.
